Hw14 calendar
b2r2/hw pull request #15
Opened 2021-07-08 22:23 UTC by b2r2

## Домашнее задание №14 «Кроликизация Календаря»

### Критерии оценки
- [ ] Makefile заполнен и пайплайн зеленый - 1 балл
- [ ] Работа с RMQ выделена в отдельный пакет, код не дублируется - 1 балл
- [ ] Реализован Рассыльщик - 2 балла
- [ ] Можно собрать сервисы одной командой (`make build`) - 1 балл
- [ ] Понятность и чистота кода - до 2 баллов

Реализован Планировщик:
- [ ] отсылает уведомления о выбранных событиях - 2 балла
- [ ] удаляет старые события - 1 балл

#### Зачёт от 7 баллов

2021-07-09 18:48 UTC, Antonboom requested changes
https://otus.ru/teacher-lk/homework/184397/9797/

Здравствуйте!

Единственный критичный вопрос - где гарантия отсылки уведомления?
Что будет, если Notify по событию не отработает? Оно попадёт в выборку в следующий раз?

2021-07-09 18:48 UTC, Antonboom commented on hw12_13_14_15_calendar/internal/config/scheduler/config.go
> +	if c.RabbitMQ.TTL == 0 {
<= 0?

2021-07-09 18:48 UTC, Antonboom commented on hw12_13_14_15_calendar/internal/config/scheduler/config.go
> +	Duration duration `json:"duration"`
`time.Duration` само не распарсится?

2021-07-09 18:48 UTC, Antonboom commented on hw12_13_14_15_calendar/internal/rmq/rmq.go
> +var retry int
где инициализируется? почему не константа или поле конфига?

2021-07-09 18:48 UTC, Antonboom commented on hw12_13_14_15_calendar/internal/rmq/rmq.go
> +func (c *Client) Notify(events []*storage.Event) {
подобное - не ответственность rmq

почему транспорт знает о событиях?

2021-07-09 18:48 UTC, Antonboom commented on hw12_13_14_15_calendar/cmd/scheduler/main.go
> +		signal.Notify(signals, syscall.SIGINT, syscall.SIGTERM)
можно заменить им mainCtx выше

2021-07-09 18:48 UTC, Antonboom commented on hw12_13_14_15_calendar/cmd/scheduler/main.go
> +				rabbit.Notify(events)
как узнать, что нужно переотправить события, если notify прошёл с ошибкой?

2021-07-09 19:44 UTC, b2r2 commented on hw12_13_14_15_calendar/internal/config/scheduler/config.go
> +	Duration duration `json:"duration"`
не парсится(

2021-07-09 19:44 UTC, b2r2 commented on hw12_13_14_15_calendar/internal/config/scheduler/config.go
> +	if c.RabbitMQ.TTL == 0 {
забыл поправить

2021-07-09 20:38 UTC, b2r2 commented on hw12_13_14_15_calendar/cmd/scheduler/main.go
> +				rabbit.Notify(events)
как вариант можно в Notify передавать канал с ошибками и писать в него и в случае ошибки, завершать работу с ошибкой

2021-07-09 20:41 UTC, b2r2 commented on hw12_13_14_15_calendar/cmd/scheduler/main.go
> +		signal.Notify(signals, syscall.SIGINT, syscall.SIGTERM)
я видимо, что-то недопонимаю. При использовании NotifyContext у меня при ctrl+C не завершается программа

2021-07-09 20:47 UTC, b2r2 commented on hw12_13_14_15_calendar/internal/rmq/rmq.go
> +func (c *Client) Notify(events []*storage.Event) {
почему?

2021-07-13 15:56 UTC, Antonboom commented on hw12_13_14_15_calendar/cmd/scheduler/main.go
> +		signal.Notify(signals, syscall.SIGINT, syscall.SIGTERM)
странно, должна завершаться

2021-07-13 15:58 UTC, Antonboom commented on hw12_13_14_15_calendar/internal/rmq/rmq.go
> +func (c *Client) Notify(events []*storage.Event) {
представьте, что rmq - это более общий сервис для работы с очередью. логично, что его API - пушнуть что-то, прочитать откуда-то

вы по сути засунули сюда notification-service, который мог бы состоять из клиента к базульке и клиента к очереди и использовать их для реализации бизнес-задачи

2021-07-13 15:59 UTC, Antonboom commented on hw12_13_14_15_calendar/cmd/scheduler/main.go
> +				rabbit.Notify(events)
я честно не понял, что вы сделали с errCh и зачем

но мой посыл был в том, что:
- Notify делает уведомление по 4-м событиям, на 2-м случается ошибка
- в следующий раз он должен повторить операцию и послать уведомление для 2-х оставшихся

сейчас кажется, что это не так, нет?

2021-07-19 17:39 UTC, Antonboom approved these changes
Принято
9 / 10

2021-07-19 17:39 UTC, Antonboom commented on hw12_13_14_15_calendar/internal/rmq/consumer.go
> +	go func() {
утечка горутины здесь и ниже

2021-07-19 18:45 UTC, merged