Hw03 frequency analysis
b2r2/hw pull request #3
Opened 2021-03-14 20:24 UTC by b2r2

## Домашнее задание №3 «Частотный анализ»

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2021-03-17 04:26 UTC, Antonboom requested changes
https://otus.ru/teacher-lk/homework/184397/9788/

Здравствуйте!
Интересная работа, но требуется рефакторинг. Много лишнего кода, увеличивающего как понимание так и алгоритмическую сложность функции.

2021-03-17 04:26 UTC, Antonboom commented on hw02_unpack_string/unpack.go
> +// ErrInvalidString return simple error by invalid string.
почему в реквест с 3-м ДЗ попало второе?

подмерживайте все и бранчуйтесь не от предыдущего ДЗ, а от master!

2021-03-17 04:26 UTC, Antonboom commented on hw03_frequency_analysis/top.go
> +type WordContainer struct {
есть ли смысл экспортировать эти структуры и их поля?

2021-03-17 04:26 UTC, Antonboom commented on hw03_frequency_analysis/top.go
> +	rg := regexp.MustCompile(`-|\p{Cyrillic}+`)
Игнорируете секцию частых ошибок в описании ДЗ

2021-03-17 04:26 UTC, Antonboom commented on hw03_frequency_analysis/top.go
> +		return []string{}
return nil

2021-03-17 04:26 UTC, Antonboom commented on hw03_frequency_analysis/top.go
> +			if position := words.FindWord(v); position != -1 {
У вас получился O(n^2), когда можно сделать O(n)

Почему бы просто не сделать слово ключом соответствующей мапы?

2021-03-17 04:26 UTC, Antonboom commented on hw03_frequency_analysis/top.go
> +			rate[words.container[i].Count] = append(rate[words.container[i].Count], words.container[i].Word)
сортировка должна только сортировать, а она у вас многое на себя берёт

2021-03-17 04:26 UTC, Antonboom commented on hw03_frequency_analysis/top.go
> +	uRate := unique(rate)
зачем это?

2021-03-17 04:26 UTC, Antonboom commented on hw03_frequency_analysis/top.go
> +	rate := make(map[int][]string)
зачем это?
вам достаточно отсортировать свои контейнеры согласно условию, а затем из них забрать первые 10 строк

2021-03-17 04:26 UTC, Antonboom commented on hw03_frequency_analysis/top.go
> +	return
где новые тесты? немного удивлён, что код выше работает. очень запутанно

2021-03-17 04:26 UTC, Antonboom commented on hw03_frequency_analysis/top.go
> +func handleString(in string) []string {
регулярку сюда бы включить?

и нельзя ли обойтись или регулярками или strings?

2021-03-19 06:34 UTC, Antonboom requested changes
Здравствуйте!

Не понимаю, стало ли лучше. Кажется, код стал ещё сложнее. Хотя в плане сортировок прогресс.
Если вы замучились, могу принять с минимумом с натяжкой, но имейте в виду, что в реальной разработке такое не прокатит.

Давайте попробуем описать тривиальный алгоритм:
1) обработали текст, избавились от лишних символов и тд. поддерживаем любые руны
2) прошлись по тексту и посчитали слова. тривиальнейшая задача, которую вы встретите на любом собеседовании. как посчитать слова в тексте? думаю, в этом может помочь `map`.
3) собрали из map набор контейнеров <слово, частота>. 
4) отсортировали
5) вернули первые 10

что думаете?

2021-03-19 06:34 UTC, Antonboom commented on hw03_frequency_analysis/go.mod
> +require github.com/stretchr/testify v1.7.0
`go mod tidy` выполняли?

2021-03-19 06:34 UTC, Antonboom commented on hw03_frequency_analysis/top.go
> +	"cyrillic":    regexp.MustCompile(`\p{Cyrillic}+`),
а зачем нужно это ограничение? в ТЗ об этом не слова

2021-03-19 06:34 UTC, Antonboom commented on hw03_frequency_analysis/top.go
> +	if rg["punctuation"].Match([]byte(s)) {
код пестрит лишними копированиями

2021-03-19 06:34 UTC, Antonboom commented on hw03_frequency_analysis/top.go
> +			if position := words.findWord(v); position != -1 {
по алгоритмической сложности лучше не стало, всё ещё неоптимально

2021-03-19 06:34 UTC, Antonboom commented on hw03_frequency_analysis/top.go
> +		if rg["cyrillic"].Match([]byte(v)) {
зачем это?

2021-03-19 06:34 UTC, Antonboom commented on hw03_frequency_analysis/top.go
> +		return nil
????

можно тест на текст из 3-х слов, я должен получить эти три слова, так как они являются top 10

2021-03-19 06:34 UTC, Antonboom commented on hw03_frequency_analysis/top.go
> +				if rg["punctuation"].Match([]byte(v)) {
нельзя ли в handleString разом сделать все преобразования?

2021-03-19 06:34 UTC, Antonboom commented on hw03_frequency_analysis/top.go
> +	sort.Slice(words.container, func(i, j int) bool {
компаратор можно сократить втрое

2021-03-19 08:15 UTC, b2r2 commented
Собственно поэтому я и записался на курс, так как самоучка-любитель и многое от меня до сих пор скрыто :)
Принимать ничего не надо. Цель не сдать, а всё-таки всё понять и усвоить.

2021-03-22 05:10 UTC, Antonboom approved these changes
Отличная работа!

Видите ли вы сами разницу между первым вариантом и последним? 
Даже количество кода уменьшилось в разы.
Супер.

Принято
10 / 10

2021-03-22 05:10 UTC, Antonboom commented on hw03_frequency_analysis/top.go
> +func setWords(res map[string]int) (words []word) {
нейминг функции не совсем удачный, непонятно, что она делает

2021-03-22 17:05 UTC, merged