Hw04 lru cache
b2r2/hw pull request #4
Opened 2021-03-29 15:29 UTC by b2r2

## Домашнее задание №4 «LRU-кэш»

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты для списка - 1 балл
- [ ] Добавлены новые юнит-тесты для кэша (включая тест на логику
выталкивания из кэша редко используемых элементов) - до 3 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2021-04-01 17:46 UTC, balabanovds requested changes
Спасибо за работу.
Еще остались замечания

Пока возвращаю на доработку

https://otus.ru/teacher-lk/homework/184397/9789/

2021-04-01 17:46 UTC, balabanovds commented on hw04_lru_cache/list.go
> +// List ...
конструктор гармоничнее смотрится после объявления типа, но это только ИМХО

2021-04-01 17:46 UTC, balabanovds commented on hw04_lru_cache/list.go
> +func (l *list) insertBackElement(e *Element) *Element {
обычно сначала экспортируемые функции, а затем внутренние

2021-04-01 17:46 UTC, balabanovds commented on hw04_lru_cache/list.go
> +func (l *list) init() List {
то есть тут Вы только длину обнуляете, а ссылки остаются, а зачем?

2021-04-01 17:46 UTC, balabanovds commented on hw04_lru_cache/cache_test.go
> +		c.Clear()
имелась ввиду не очистка кеша, а выдавливание

2021-04-01 17:46 UTC, balabanovds commented on hw04_lru_cache/cache.go
> +	lock     sync.RWMutex
а почему решили использовать RWMutex?

2021-04-01 17:46 UTC, balabanovds commented on hw04_lru_cache/cache.go
> +// NewCache ...
то есть я могу создать кеш нулевой или отрицательной длины?

2021-04-01 19:43 UTC, b2r2 commented
> Спасибо за работу.
> 
> Еще остались замечания и не написаны тесты на кеш
> 
> 
> 
> Пока возвращаю на доработку
> 
> 
> 
> https://otus.ru/teacher-lk/homework/184397/9789/

А в чем заключаются замечания?

2021-04-02 04:51 UTC, balabanovds approved these changes
Хорошо!
8/10

Оценку можно будет пересмотреть если решите поправить код

2021-04-02 04:51 UTC, balabanovds commented on hw04_lru_cache/cache.go
> +		return nil
но мы же должны сообщить клиенту об ошибке, невежливо просто так бросаться нилом :)
может сигнатуру поменять?

2021-04-02 04:51 UTC, balabanovds commented on hw04_lru_cache/cache_test.go
> +		}
то есть после первого цикла в кеше будут 7,8,9, а затем Вы проверяете в цикле 10 раз есть ли там 1. хм.. 🧐 
а так выдавливание проверено.. да

еще бы круто сделать тест на логику выталкивания из кэша редко используемых элементов!

2021-04-06 16:55 UTC, merged