Hw05 parallel execution
b2r2/hw pull request #5
Opened 2021-04-11 14:42 UTC by b2r2

## Домашнее задание №5 «Параллельное исполнение»

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2021-04-12 15:36 UTC, kulti requested changes
Рамиль, решение некорректное. В ДЗ описано другое поведение.

У текущего решения есть большой плюс — простота и компактность. Постарайтесь их сохранить, когда будете переделывать.

2021-04-12 15:36 UTC, kulti commented on hw05_parallel_execution/run.go
> +		go func() {
Это решение запускает len(tasks) горутин, если нет ошибок. Это противоречит первому пункту из ДЗ:
> количество создаваемых горутин не должно зависеть от числа заданий, т.е. функция должна запусать n горутин для параллельно обработки заданий и, возможно, еще несколько вспомогательных горутин;

2021-04-12 15:36 UTC, kulti commented on hw05_parallel_execution/run_test.go
> +		require.Truef(t, errors.Is(err, ErrErrorsLimitExceeded), "actual err - %v", err)
Вас не смущает поведение этого теста? Мне кажется странным, что отрицательное m приводит к ошибке, что превышен лимит ошибок. Не вижу связи и логики в этом.

2021-04-12 15:36 UTC, kulti commented on hw05_parallel_execution/run.go
> +		if atomic.LoadInt32(&errCount) >= rune(m) {
При чем тут rune?

2021-04-12 17:21 UTC, kulti commented on hw05_parallel_execution/run_test.go
> +		require.Truef(t, errors.Is(err, ErrErrorsLimitExceeded), "actual err - %v", err)
Обсудили в слаке. Моя невнимательность — вопрос снимается.

2021-04-14 05:11 UTC, kulti approved these changes
Рамиль, теперь решение корректное. Есть пара шерховатостей, которые можно упростить.

ДЗ принято — 9/10. Рекомендую посмотреть разбор ДЗ — https://youtu.be/lD7q5S3BVto.

2021-04-14 05:11 UTC, kulti commented on hw05_parallel_execution/run.go
> +	if atomic.LoadInt32(&errCount) >= int32(m) {
А здесь точно нужен atomic? От какой конкурирующей записи он защищает?

2021-04-14 05:11 UTC, kulti commented on hw05_parallel_execution/run.go
> +					return
Этот return выглядит опасно. Неочевидно, что в этот момент уже точно не будет записей в канал taskCh.

Мне кажется, что записей больше не должно происходить, но если они будут, то пишущая горутина навсегда зависнет. Сложно сказать со 100% уверенностью, что все хорошо будет.

А если убрать этот if, что будет?

2021-04-14 06:51 UTC, b2r2 commented on hw05_parallel_execution/run.go
> +	if atomic.LoadInt32(&errCount) >= int32(m) {
Он бессмысленный, согласен. Поправлю

2021-04-14 10:40 UTC, b2r2 commented on hw05_parallel_execution/run.go
> +					return
Если if убрать, то не пройдет первый тест по условию `если в первых m задачах происходят ошибки, то всего выполнится не более n+m задач.`, но можно return заменить на break, хотя по сути это одно и тоже

2021-04-14 17:03 UTC, merged

2021-04-15 05:36 UTC, kulti commented on hw05_parallel_execution/run.go
> +					return
Разве? На 41 строчке будет выход из цикла записи тасок в канал. Т.е. лишних задач на обработку не придет. В итоге будет n+m-1 в худшем случае.